# Generated by Django 4.1.7 on 2023-02-24 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage_bonus', models.DecimalField(decimal_places=2, default=50.0, max_digits=4)),
                ('total_hours', models.IntegerField(default=8)),
                ('shift_date', models.DateField(default=datetime.datetime(2023, 2, 24, 11, 38, 21, 952866))),
            ],
        ),
        migrations.CreateModel(
            name='ShiftsEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employees')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shifts')),
            ],
            options={
                'unique_together': {('employee', 'shift')},
            },
        ),
        migrations.AddField(
            model_name='shifts',
            name='employees_shift',
            field=models.ManyToManyField(related_name='shifts', through='core.ShiftsEmployees', to='core.employees'),
        ),
    ]
